// Run with NODE_PATH pointing to a Playwright installation and a local server on :8000.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1280,height:1000},acceptDownloads:true});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=160;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,200,160);x.fillStyle='#e45235';x.fillRect(50,30,100,100);x.fillStyle='#eeeeee';x.fillRect(0,0,20,20);return c.toDataURL().split(',')[1];});
 await page.locator('#upload').setInputFiles({name:'tile.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await page.waitForFunction(()=>!!original);
 assert.equal(await page.evaluate(()=>source.width),200);
 await page.locator('#source').click({position:{x:30,y:10}});
 assert.equal(await page.evaluate(()=>pctx.getImageData(30,10,1,1).data[3]),0);
 assert.equal(await page.evaluate(()=>pctx.getImageData(60,60,1,1).data[3]),255);
 await page.locator('#threshold').fill('0');
 assert.equal(await page.evaluate(()=>pctx.getImageData(5,5,1,1).data[3]),255);
 await page.locator('#threshold').fill('40');
 assert.equal(await page.evaluate(()=>pctx.getImageData(5,5,1,1).data[3]),0);
 await page.locator('#add').click(); await page.locator('#add').click();
 assert.equal(await page.evaluate(()=>tiles.length),2);
 const before=await page.evaluate(()=>({x:tiles[1].x,y:tiles[1].y}));
 const box=await page.locator('#board').boundingBox();
 await page.mouse.move(box.x+before.x/1200*box.width,box.y+before.y/800*box.height); await page.mouse.down(); await page.mouse.move(box.x+(before.x+120)/1200*box.width,box.y+(before.y+80)/800*box.height);await page.mouse.up();
 assert.ok(await page.evaluate(()=>Math.abs(tiles[1].x-672)<2));
 await page.locator('#left').click();assert.equal(await page.evaluate(()=>tiles[1].angle),330);
 await page.locator('#right').click();assert.equal(await page.evaluate(()=>tiles[1].angle),0);
 await page.locator('#right').click();await page.locator('#flip').click();await page.locator('#grow').click();
 assert.ok(await page.evaluate(()=>tiles[1].angle===30&&tiles[1].flip&&tiles[1].scale===1.2));
 await page.locator('#shrink').click();assert.equal(await page.evaluate(()=>tiles[1].scale),1);
 const download=page.waitForEvent('download');await page.locator('#save').click();const file=await download;assert.ok(file.suggestedFilename().endsWith('.png'));
 await page.waitForFunction(()=>!!downloadUrl);
 const exported=await page.evaluate(async()=>{const image=new Image();image.src=downloadUrl;await image.decode();const c=document.createElement('canvas');c.width=1200;c.height=800;const x=c.getContext('2d');x.drawImage(image,0,0);const expected=document.createElement('canvas');expected.width=1200;expected.height=800;const e=expected.getContext('2d');e.fillStyle='white';e.fillRect(0,0,1200,800);for(const t of tiles){e.save();e.translate(t.x,t.y);e.rotate(t.angle*Math.PI/180);e.scale(t.flip?-t.scale:t.scale,t.scale);e.drawImage(t.asset.canvas,-t.w/2,-t.h/2,t.w,t.h);e.restore();}const a=x.getImageData(0,0,1200,800).data,b=e.getImageData(0,0,1200,800).data;return {width:image.width,height:image.height,equal:a.every((v,i)=>v===b[i])};});
 assert.deepEqual(exported,{width:1200,height:800,equal:true});
 await page.locator('#delete').click(); assert.equal(await page.evaluate(()=>tiles.length),1);
 page.once('dialog',d=>d.accept());await page.locator('#reset').click();assert.equal(await page.evaluate(()=>tiles.length),0);
 await page.locator('#restore').click();assert.equal(await page.evaluate(()=>pctx.getImageData(30,10,1,1).data[3]),255);
 // Three separated backgrounds plus a white interior enclosed by a black outline.
 const regions=await page.evaluate(()=>{
   const c=document.createElement('canvas');c.width=200;c.height=160;const x=c.getContext('2d');
   x.fillStyle='white';x.fillRect(0,0,200,160);
   x.fillStyle='#eeeeee';x.fillRect(0,0,20,20);x.fillRect(180,0,20,20);
   x.fillStyle='black';x.fillRect(95,0,10,160);x.fillRect(105,75,95,10);
   x.fillRect(25,45,50,60);x.fillStyle='white';x.fillRect(30,50,40,50);
   return c.toDataURL().split(',')[1];
 });
 await page.locator('#upload').setInputFiles({name:'regions.png',mimeType:'image/png',buffer:Buffer.from(regions,'base64')});
 await page.waitForFunction(()=>original.data[(80*200+100)*4]===0);
 const alpha=(x,y)=>page.evaluate(({x,y})=>pctx.getImageData(x,y,1,1).data[3],{x,y});
 await page.locator('#source').click({position:{x:40,y:20}});
 assert.equal(await alpha(10,30),0);assert.equal(await alpha(5,5),0);
 assert.equal(await alpha(45,70),255,'enclosed white interior must survive');
 assert.equal(await alpha(150,30),255);assert.equal(await alpha(150,120),255);
 await page.locator('#source').click({position:{x:150,y:30}});
 assert.equal(await alpha(150,30),0);assert.equal(await alpha(190,5),0);
 assert.equal(await alpha(150,120),255);assert.equal(await alpha(45,70),255);
 await page.locator('#threshold').fill('0');
 assert.equal(await alpha(190,5),255,'latest fill must recalculate');
 assert.equal(await alpha(5,5),0,'previous fill must remain deleted');
 await page.locator('#threshold').fill('40');
 await page.locator('#source').click({position:{x:150,y:120}});
 assert.equal(await alpha(150,120),0);assert.equal(await alpha(45,70),255);
 assert.equal(await alpha(100,80),255,'black divider must survive');
 const beforeTransparentClick=await page.evaluate(()=>Array.from(pctx.getImageData(0,0,200,160).data));
 await page.locator('#source').click({position:{x:150,y:30}});
 assert.deepEqual(await page.evaluate(()=>Array.from(pctx.getImageData(0,0,200,160).data)),beforeTransparentClick);
 await page.locator('#restore').click();
 assert.ok(await page.evaluate(()=>pctx.getImageData(0,0,200,160).data.every((v,i)=>v===original.data[i])),'restore must match every original pixel');
 // A fresh fill after restore must not retain any earlier removal.
 await page.locator('#source').click({position:{x:150,y:120}});
 assert.equal(await alpha(10,30),255);assert.equal(await alpha(150,30),255);assert.equal(await alpha(150,120),0);
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});const touch=await mobile.newPage();await touch.goto('http://127.0.0.1:8000');
 await touch.locator('#upload').setInputFiles({name:'tile.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await touch.waitForFunction(()=>!!original);
 await touch.locator('#source').tap({position:{x:30,y:10}});await touch.locator('#add').click();await touch.locator('#board').scrollIntoViewIfNeeded();
 const r=await touch.locator('#board').boundingBox();const pos=await touch.evaluate(()=>({x:tiles[0].x,y:tiles[0].y}));const x=r.x+pos.x/1200*r.width,y=r.y+pos.y/800*r.height;
 const cdp=await mobile.newCDPSession(touch);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+35,y:y+20}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await touch.evaluate(()=>tiles[0].x>600));
 assert.ok(await touch.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:'/private/tmp/tiling-desktop.png',fullPage:true});await touch.screenshot({path:'/private/tmp/tiling-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: upload, background selection, threshold, add, mouse/touch drag, rotations, flip, scale, delete, reset, PNG pixel comparison, mobile overflow, enclosed white preservation, three cumulative fills, latest threshold isolation, transparent-click no-op, exact full restore.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
